name: Rust

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test (envoy:${{ matrix.version.envoy_image_tag }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version:
        - envoy_image_tag: v1.31-latest
        - envoy_image_tag: v1.30-latest
        - envoy_image_tag: v1.29-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        components: rustfmt, clippy

    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-registry-

    - name: Cache cargo index
      uses: actions/cache@v4
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-index-

    - name: Clippy
      run: cargo clippy --all --examples  -- -D warnings

    - name: Format
      run: cargo fmt --all -- --check

    - name: Build
      run: |
        cargo build
        cargo build --examples

    - name: Run tests
      run: | 
        cargo test
        cargo test --examples

    - name: Install Envoy
      run: |
        export ENVOY_BIN_DIR=$HOME/envoy/bin
        mkdir -p $ENVOY_BIN_DIR
        docker run -v $ENVOY_BIN_DIR:/work/go-sdk -w /work/go-sdk \
          --entrypoint /bin/cp ghcr.io/mathetake/envoy:${{ matrix.version.envoy_image_tag }} /usr/local/bin/envoy .
        echo $ENVOY_BIN_DIR >> $GITHUB_PATH

    - name: Conformance tests
      run: go run github.com/mathetake/envoy-dynamic-modules-sdk-conformance-tests@main --shared-library-path=./target/debug/examples/libexample.so --target=TestHelloWorld
  